#!/bin/bash

## Install all pkgs required for xmonad to run at full capacity

xmonad_pkgs=(autorandr feh xorg-server xorg-xset libpulse flameshot
             playerctl acpid ttf-symbola-free ttf-symbola-free
             ttf-dejavu numlockx picom i3lock-color
             xorg-xrandr xss-lock)

yay --needed --noconfirm --norebuild --removemake -S "${xmonad_pkgs[@]}"
