#!/bin/bash

# Print list of packages to be installed via yay

this_dir=$(dirname "$0")

mapfile -t local < <("$this_dir/.query_pkgs" "AUR")

if ! yay -Si "${local[@]}" > /dev/null; then
    echo "At least one local package doesn't exist."
    exit 1
fi

echo "${local[@]}"
